spring:
  application:
    name: spring-gift


  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: ${JWT_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

mmse:
  upload-dir: uploads/mmse
  tts-base-url: https://cdn.example.com/audio/mmse
  export-dir: ./uploads/mmse/export

demographics:
  export-dir: ./uploads/demographics/export

# Gemini API Key 환경 변수로 불러옴
gemini:
  api-key: ${GEMINI_API_KEY}

